# Site settings
author: Cedric Goddard
title: "Why I decided  to study Software Engineering"
header-img: img/home-bg.png
email: 8ceg6@comcast.net
copyright_name: Cedric Goddard
description: > # this means to ignore newlines until "baseurl:"
  All ABOUT MY WHY 
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  8ceg6

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
